// <auto-generated />
namespace SDP2241A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class genres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genres));
        
        string IMigrationMetadata.Id
        {
            get { return "202408020235247_genres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
